name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
            ~/.cache/yarn
          key: ${{ runner.os }}-gradle-clear-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - uses: actions/checkout@v4

      - name: Publish Web App
        uses: openMF/KMP-web-publish-action@v1.0.0
        with:
          web_package_name: 'composeApp'